name: rekrutmen

services:
  nginx:
    image: openresty/openresty:alpine
    container_name: rekrutmen-nginx
    restart: always
    ports:
      - "8082:80"
    volumes:
      - ./src/rekrutmen:/var/www/html/rekrutmen
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /media/foto_kar:/media/foto_kar
      - /media/forqsd:/media/forqsd
      - /media/fortrainingpsn:/media/fortrainingpsn
    depends_on:
      - app83
    networks:
      - appnet
      - proxy-net

  app83:
    build:
      context: .
      dockerfile: ./docker/php83/Dockerfile
    image: rekrutmen-app83
    container_name: rekrutmen-php83
    restart: always
    working_dir: /var/www/html/rekrutmen
    volumes:
      - ./src/rekrutmen:/var/www/html/rekrutmen
      - ./docker/php83/php.ini:/usr/local/etc/php/conf.d/99-custom.ini:ro
      - /media/foto_kar:/media/foto_kar
      - /media/forqsd:/media/forqsd
      - /media/fortrainingpsn:/media/fortrainingpsn
      - /media/forqsd/rekrutmen/berkas:/media/forqsd/rekrutmen/berkas
      - /media/forqsd/rekrutmen/bypass:/media/forqsd/rekrutmen/bypass
      - /media/forqsd/rekrutmen/calonkandidat:/media/forqsd/rekrutmen/calonkandidat
      - /media/forqsd/rekrutmen/foto:/media/forqsd/rekrutmen/foto
      - /media/forqsd/rekrutmen/fotoProfil:/media/forqsd/rekrutmen/fotoProfil
      - /media/forqsd/rekrutmen/idealkarytk:/media/forqsd/rekrutmen/idealkarytk
      - /media/forqsd/rekrutmen/ttd:/media/forqsd/rekrutmen/ttd
      - /media/forqsd/rekrutmen/ttdbynik:/media/forqsd/rekrutmen/ttdbynik
      - /media/forqsd/rekrutmen/ttdpgd:/media/forqsd/rekrutmen/ttdpgd
    environment:
      TZ: Asia/Jakarta
      CI_ENV: ${CI_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST_1: ${DB_HOST}
      DB_PORT_1: ${DB_PORT}
      DB_USER_1: ${DB_USER}
      DB_PASS_1: ${DB_PASS}
      DB_NAME_1: ${DB_NAME}
      DB_HOST_2: ${DB_HOST}
      DB_PORT_2: ${DB_PORT}
      DB_USER_2: ${DB_USER}
      DB_PASS_2: ${DB_PASS}
      DB_NAME_2: ${DB_NAME}
      DB_HOST_3: ${DB_HOST}
      DB_PORT_3: ${DB_PORT}
      DB_USER_3: ${DB_USER}
      DB_PASS_3: ${DB_PASS}
      DB_NAME_3: ${DB_NAME}
      DB_HOST_4: ${DB_HOST}
      DB_PORT_4: ${DB_PORT}
      DB_USER_4: ${DB_USER}
      DB_PASS_4: ${DB_PASS}
      DB_NAME_4: ${DB_NAME}
      DB_HOST_5: ${DB_HOST}
      DB_PORT_5: ${DB_PORT}
      DB_USER_5: ${DB_USER}
      DB_PASS_5: ${DB_PASS}
      DB_NAME_5: ${DB_NAME}
    networks:
      - appnet

networks:
  appnet:
  proxy-net:
    external: true
