server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index index.php index.html;

    client_max_body_size 50M;

     location = / {
        return 301 /rekrutmen/;
    }

    location /rekrutmen {
        try_files $uri $uri/ /rekrutmen/index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass app83:9000;
    }

    location ~* ^/rekrutmen/(application|system) {
        deny all;
    }

    location ~ /\. {
        deny all;
    }
}
